# Usando uma imagem do PHP com suporte ao FPM
FROM php:8.2-fpm

# Instalando o Nginx
RUN apt-get update && apt-get install -y nginx \
    && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev \
    && apt-get install -y mariadb-client \
    && docker-php-ext-install mysqli pdo pdo_mysql

# Removendo arquivos desnecessários para reduzir a imagem
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Copiando o arquivo de configuração do Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Copiando os arquivos do site para a pasta padrão do Nginx
COPY public /usr/share/nginx/html


# Comando para iniciar o PHP-FPM e o Nginx juntos
CMD service nginx start && php-fpm
